import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const SUPABASE_URL              = Deno.env.get('SUPABASE_URL')!
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const SLACK_WEBHOOK_URL         = Deno.env.get('SLACK_WEBHOOK_URL')!
const BETA_ACTION_SECRET        = Deno.env.get('BETA_ACTION_SECRET')!

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

const LINK_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000 // 7 days

// Mirrors notify-beta-request's signAction — verifies this link was
// actually generated by us (not forged or guessed) and hasn't gone stale.
async function verifyAction(id: string, action: string, ts: string, sig: string): Promise<boolean> {
  const tsNum = Number(ts)
  if (!Number.isFinite(tsNum) || Date.now() - tsNum > LINK_MAX_AGE_MS) return false

  const enc = new TextEncoder()
  const key = await crypto.subtle.importKey(
    'raw', enc.encode(BETA_ACTION_SECRET), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
  )
  const expectedSig = await crypto.subtle.sign('HMAC', key, enc.encode(`${id}:${action}:${ts}`))
  const expectedHex = Array.from(new Uint8Array(expectedSig)).map(b => b.toString(16).padStart(2, '0')).join('')

  if (expectedHex.length !== sig.length) return false
  let diff = 0
  for (let i = 0; i < expectedHex.length; i++) diff |= expectedHex.charCodeAt(i) ^ sig.charCodeAt(i)
  return diff === 0
}

serve(async (req) => {
  try {
    const url    = new URL(req.url)
    const id     = url.searchParams.get('id')
    const action = url.searchParams.get('action') // 'approve' | 'deny'
    const ts     = url.searchParams.get('ts')
    const sig    = url.searchParams.get('sig')

    if (!id || !action || !ts || !sig) {
      return new Response('Missing id, action, ts, or sig', { status: 400 })
    }

    if (!(await verifyAction(id, action, ts, sig))) {
      return htmlResponse('Link expired or invalid', 'This approve/deny link is no longer valid — check Slack for a current one, or use the Beta Admin page in the app.')
    }

    // Fetch the beta request row
    const { data: betaRequest, error: fetchError } = await supabase
      .from('beta_requests')
      .select('*')
      .eq('id', id)
      .maybeSingle()

    if (fetchError || !betaRequest) {
      return htmlResponse('❌ Request not found.', 'Something went wrong — request not found.')
    }

    // Guard: already processed
if (betaRequest.status === 'approved') {
  return htmlResponse('Already approved', `${betaRequest.email} was already approved.`)
}
if (betaRequest.status === 'denied') {
  return htmlResponse('Already denied', `${betaRequest.email} was already denied.`)
}

if (action === 'deny') {
  await supabase
    .from('beta_requests')
    .update({ status: 'denied' })
    .eq('id', id)

  await notifySlack(`❌ *${betaRequest.name || betaRequest.email}* was denied.`)
  return htmlResponse('Denied', `${betaRequest.email} has been denied.`)
}

if (action === 'approve') {
  const { error: updateError } = await supabase
    .from('beta_requests')
    .update({ status: 'approved' })
    .eq('id', id)

      if (updateError) {
        console.error('Update error:', updateError)
        return htmlResponse('Error', 'Failed to update approval status.')
      }

      // 2. Send Supabase invite email (magic link)
      const { error: inviteError } = await supabase.auth.admin.inviteUserByEmail(
        betaRequest.email,
        {
          data: {
  full_name:      betaRequest.name || '',
  workspace_name: betaRequest.name ? `${betaRequest.name}'s Workspace` : 'My Workspace',
},
          redirectTo: 'https://app.gabspace.io',
        }
      )

      if (inviteError) {
        console.error('Invite error:', inviteError)
        // Still approved in DB — just notify Slack the invite failed
        await notifySlack(`⚠️ *${betaRequest.email}* approved but invite email failed: ${inviteError.message}`)
        return htmlResponse('Approved (invite failed)', `${betaRequest.email} approved but invite email failed. Check Supabase.`)
      }

      // 3. Confirm back to Slack
      await notifySlack(`✅ *${betaRequest.full_name || betaRequest.email}* approved — invite sent to ${betaRequest.email}`)

      return htmlResponse('✅ Approved!', `Invite sent to ${betaRequest.email}. They'll receive a magic link to join Gabspace.`)
    }

    return new Response('Unknown action', { status: 400 })

  } catch (err) {
    console.error('approve-beta-request error:', err)
    return new Response('Internal error', { status: 500 })
  }
})

// ── Helpers ──────────────────────────────────────────────────────────────────

async function notifySlack(text: string) {
  try {
    await fetch(SLACK_WEBHOOK_URL, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ text }),
    })
  } catch (e) {
    console.error('Slack notify error:', e)
  }
}

// Supabase's Edge Runtime sandboxes HTML served directly from *.supabase.co
// (forces Content-Type: text/plain + a CSP that blocks rendering), so instead
// of inlining a confirmation page here, redirect to one on our own domain.
function htmlResponse(title: string, message: string) {
  const url = new URL('https://app.gabspace.io/')
  url.searchParams.set('beta-status', '1')
  url.searchParams.set('title', title)
  url.searchParams.set('message', message)
  return Response.redirect(url.toString(), 302)
}
