import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

const SLACK_WEBHOOK_URL  = Deno.env.get('SLACK_WEBHOOK_URL')!
const SUPABASE_URL       = Deno.env.get('SUPABASE_URL')!
const BETA_ACTION_SECRET = Deno.env.get('BETA_ACTION_SECRET')!
const DB_WEBHOOK_SECRET  = Deno.env.get('DB_WEBHOOK_SECRET')!

// Signs the approve/deny link so approve-beta-request can verify it was
// actually generated by us, rather than trusting a bare (guessable-in-
// principle, and trivially forwardable/prefetchable) id + action pair in
// a plain GET URL. See approve-beta-request for the verifying half.
async function signAction(id: string, action: string, ts: number): Promise<string> {
  const enc = new TextEncoder()
  const key = await crypto.subtle.importKey(
    'raw', enc.encode(BETA_ACTION_SECRET), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
  )
  const sig = await crypto.subtle.sign('HMAC', key, enc.encode(`${id}:${action}:${ts}`))
  return Array.from(new Uint8Array(sig)).map(b => b.toString(16).padStart(2, '0')).join('')
}

serve(async (req) => {
  try {
    // This is invoked by a Supabase Database Webhook, not a browser -
    // verify_jwt only checks for *some* valid JWT (the anon key
    // qualifies), so without this anyone with the anon key could POST a
    // forged {record: {...}} body and inject arbitrary attacker-controlled
    // content into our internal Slack channel. The webhook config must
    // send this same secret as the `x-webhook-secret` header.
    if (req.headers.get('x-webhook-secret') !== DB_WEBHOOK_SECRET) {
      return new Response('Unauthorized', { status: 401 })
    }

    const payload = await req.json()

    // Supabase DB webhook sends the new row under payload.record
    const record = payload.record
    if (!record) {
      return new Response('No record', { status: 400 })
    }

    const {
  id,
  email,
  name,
  creative_type,
  social_link,
  how_heard,
  created_at,
} = record

    // Build the approve/deny URLs — these hit our second Edge Function.
    // Signed + timestamped so a forwarded/leaked link can't be replayed
    // indefinitely and can't be forged for a different id/action.
    const baseUrl = `${SUPABASE_URL}/functions/v1/approve-beta-request`
    const ts = Date.now()
    const approveSig = await signAction(id, 'approve', ts)
    const denySig    = await signAction(id, 'deny', ts)
    const approveUrl = `${baseUrl}?id=${id}&action=approve&ts=${ts}&sig=${approveSig}`
    const denyUrl    = `${baseUrl}?id=${id}&action=deny&ts=${ts}&sig=${denySig}`

    const formattedDate = new Date(created_at).toLocaleDateString('en-US', {
      month: 'short', day: 'numeric', year: 'numeric',
    })

    const slackBody = {
      blocks: [
        {
          type: 'header',
          text: {
            type: 'plain_text',
            text: '✨ New Beta Request',
            emoji: true,
          },
        },
        {
          type: 'section',
          fields: [
  { type: 'mrkdwn', text: `*Name*\n${name || '—'}` },
  { type: 'mrkdwn', text: `*Email*\n${email}` },
  { type: 'mrkdwn', text: `*Creative type*\n${creative_type || '—'}` },
  { type: 'mrkdwn', text: `*Submitted*\n${formattedDate}` },
],
        },
        ...(social_link ? [{
  type: 'section',
  fields: [
    { type: 'mrkdwn', text: `*Social / Website*\n${social_link}` },
  ],
}] : []),
...(how_heard ? [{
  type: 'section',
  text: { type: 'mrkdwn', text: `*How they heard about Gabspace*\n${how_heard}` },
}] : []),
        { type: 'divider' },
        {
          type: 'actions',
          elements: [
            {
              type: 'button',
              text: { type: 'plain_text', text: '✅ Approve', emoji: true },
              style: 'primary',
              url: approveUrl,
            },
            {
              type: 'button',
              text: { type: 'plain_text', text: '❌ Deny', emoji: true },
              style: 'danger',
              url: denyUrl,
            },
          ],
        },
      ],
    }

    const slackRes = await fetch(SLACK_WEBHOOK_URL, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify(slackBody),
    })

    if (!slackRes.ok) {
      const text = await slackRes.text()
      console.error('Slack error:', text)
      return new Response('Slack error', { status: 500 })
    }

    return new Response('OK', { status: 200 })
  } catch (err) {
    console.error('notify-beta-request error:', err)
    return new Response('Internal error', { status: 500 })
  }
})
