-- Superseded by 20260101000000_baseline_schema.sql, which already contains
-- the item_date column this migration added.
-- Kept as a no-op so its version stays in sync with production's tracked history.
